### ISSUE TITLE
Provide access to the glyphs as SVG

### ISSUE THREAD

**Issue by lpugin** [Edirom/SMuFL-Browser#7]
Currently, we can access the glyphs as PNG. For example

https://smufl-browser.edirom.de/accdnRH3RanksPiccolo.png

Would it be complicated to have the same but with SVG?

Having looked that image generation process, it uses Graphics2D to convert the glyphs to PNG. Doing the same for SVG would probably not work, so the adjustment might be quite significant.

**Comment by peterstadler** [comment]
Just had a quick look: There's already an SVG font at https://github.com/steinbergmedia/bravura/tree/master/redist/svg. Maybe it would be possible to extract the individual glyphs from there (rather than generating them from the OTF font)?

**Comment by lpugin** [comment]
Yes, I think that would be a good option. This is more or less what we do in Verovio to extract the SVG glyphs. Two remarks:
* In Verovio we just extract the `<glyph>` elements and turn them into `<symbol>` elements that we embed in the SVG generated. We do not generate independent SVG images
* The Y axis direction is reverse in SVG font than in SVG images, so for each glyph extracted we add a `@transform="scale(1,-1)"` to the `<path>`. You will probably have to do the same.

**Comment by peterstadler** [comment]
Thanks for the hints! I manage to turn those `<glyph>`s into `<path>`s but the offsets (and viewBox) are giving me headaches. E.g.
```xml
<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" viewBox="0 0 1000 1000">
    <path transform="scale(1,-1) translate(0, -781)" fill="yes" stroke="black" stroke-width="1" d="M391 0c-214 0 -391 174 -391 391c0 213 175 391 391 391c215 0 391 -173 391 -391c0 -215 -172 -391 -391 -391zM61 532h661c-57 132 -187 218 -331 218c-145 0 -273 -85 -330 -218zM391 703c35 0 62 -28 62 -62s-27 -62 -62 -62c-34 0 -62 28 -62 62s28 62 62 62z
        M49 282h685c11 35 16 71 16 109c0 37 -5 74 -16 109h-685c-11 -35 -17 -72 -17 -109c0 -38 6 -74 17 -109zM61 250c57 -133 185 -218 330 -218c144 0 274 86 331 218h-661z" />
</svg>
```

The `translate(0, -781)` is added to fix the `@horiz-adv-x="781"` but still the resulting shape is out of the viewBox. Any ideas?

**Comment by peterstadler** [comment]
As an alternative, @kepper found https://github.com/icons8/svg-caster. That could be applied at build time to create the individual glyphs.

**Comment by lpugin** [comment]
I think that in order to get the offsets and sizes right you need to use the bounding box values given in the metadata file:
https://github.com/steinbergmedia/bravura/blob/master/redist/bravura_metadata.json

I looked for the Leipzig (Bravura should be the same) and the values in the metadata * 250 will give you the size and the offsets. For example, for the `gClef` we have
```json
        "gClef": {
            "bBoxNE": [
                2.584,
                4.332
            ],
            "bBoxSW": [
                -0.004,
                -2.62
            ]
        },
```

The width is `(bBoxSW[0] - bBoxNE[0]) * 250 = 647` and the height  `(bBoxSW[1] - bBoxNE[1]) * 250 = 1738`

The offset (in `translate`) is `-bBoxSW[0] * 250 = 1` and `bBoxNE[1] * 250 = 1083`

This is what I get for the [gClef](https://gist.githubusercontent.com/lpugin/0d5ea769f995e68719d96e9513cadb71/raw/46db9929e026580e6b68ffae3c02c21f05ab3e5e/gClef.svg)

```xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="647" height="1738">
   <path transform="translate(1, 1083) scale(1,-1)" d="M441 -245c-23 -4 -48 -6 -76 -6c-59 0 -102 7 -130 20c-88 42 -150 93 -187 154c-26 44 -43 103 -48 176c0 6 -1 13 -1 19c0 54 15 111 45 170c29 57 65 106 110 148s96 85 153 127c-3 16 -8 46 -13 92c-4 43 -5 73 -5 89c0 117 16 172 69 257c34 54 64 82 89 82 c21 0 43 -30 69 -92s39 -115 41 -159v-15c0 -109 -21 -162 -67 -241c-13 -20 -63 -90 -98 -118c-13 -9 -25 -19 -37 -29l31 -181c8 1 18 2 28 2c58 0 102 -12 133 -35c59 -43 92 -104 98 -184c1 -7 1 -15 1 -22c0 -123 -87 -209 -181 -248c8 -57 17 -110 25 -162 c5 -31 6 -58 6 -80c0 -30 -5 -53 -14 -70c-35 -64 -88 -99 -158 -103c-5 0 -11 -1 -16 -1c-37 0 -72 10 -108 27c-50 24 -77 59 -80 105v11c0 29 7 55 20 76c18 28 45 42 79 44h6c49 0 93 -42 97 -87v-9c0 -51 -34 -86 -105 -106c17 -24 51 -36 102 -36c62 0 116 43 140 85 c9 16 13 41 13 74c0 20 -1 42 -5 67c-8 53 -18 106 -26 159zM461 939c-95 0 -135 -175 -135 -286c0 -24 2 -48 5 -71c50 39 92 82 127 128c40 53 60 100 60 140v8c-4 53 -22 81 -55 81h-2zM406 119l54 -326c73 25 110 78 110 161c0 7 0 15 -1 23c-7 95 -57 142 -151 142h-12 zM382 117c-72 -2 -128 -47 -128 -120v-7c2 -46 43 -99 75 -115c-3 -2 -7 -5 -10 -10c-70 33 -116 88 -123 172v11c0 68 44 126 88 159c23 17 49 29 78 36l-29 170c-21 -13 -52 -37 -92 -73c-50 -44 -86 -84 -109 -119c-45 -69 -67 -130 -67 -182v-13c5 -68 35 -127 93 -176 s125 -73 203 -73c25 0 50 3 75 9c-19 111 -36 221 -54 331z" />
</svg>
```

**Comment by lpugin** [comment]
Correction: the offset is -bBoxSW[0] * 250 (corrected above)

**Comment by peterstadler** [comment]
Thanks @lpugin for the feature request and your help!
It's now live in the dev branch and deployed at https://smufl-browser.edirom.de/ 

For the record, I'm using the Bravura.svg font for the SVG glyphs while for the PNG images we use BravuraText.otf. I don't think there are major differences but in the offsets? Because of these offsets I had to use Bravura.svg since the [font metadata file](https://github.com/steinbergmedia/bravura/blob/master/redist/bravura_metadata.json) does only match the Bravura font?
Second, for some glyphs the offsets seem to be a bit off: see e.g. https://smufl-browser.edirom.de/E0AB.svg

**Comment by lpugin** [comment]
> Second, for some glyphs the offsets seem to be a bit off: see e.g. https://smufl-browser.edirom.de/E0AB.svg

Maybe the metadata file is not up-to-date?
